export default Object.freeze({
    MEMBER: {
        EDIT_OWN_MESSAGES: "EDIT_OWN_MESSAGES",
        DELETE_OWN_MESSAGES: "DELETE_OWN_MESSAGES",
        SEND_PHOTOS: "SEND_PHOTOS",
        SEND_FILES: "SEND_FILES",
        CHANGE_GROUP_INFO: "CHANGE_GROUP_INFO",
        ADD_NEW_MEMBER: "ADD_NEW_MEMBER" 
    },
    ADMIN: {
        DELETE_MESSAGES: "DELETE_MESSAGES",
        DELETE_MEMBERS: "DELETE_MEMBERS",
        PROMOTE_TO_ADMIN: "PROMOTE_TO_ADMIN",
    },
    OWNER: {}
});